name: Count Git clones
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */5 * *"

jobs:
  count-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: minimod
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p minimod/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.TRAFFIC }}" https://api.github.com/repos/warp9seq/minimod/traffic/clones > minimod/${YEAR}/${DATE}.json
      - name: openfish
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p openfish/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.TRAFFIC }}" https://api.github.com/repos/warp9seq/openfish/traffic/clones > openfish/${YEAR}/${DATE}.json
      - name: kuva
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p kuva/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.KUVA_BUTTERYEEL_BLUECRAB }}" https://api.github.com/repos/Psy-Fer/kuva/traffic/clones > kuva/${YEAR}/${DATE}.json
      - name: buttery-eel
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p buttery-eel/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.KUVA_BUTTERYEEL_BLUECRAB }}" https://api.github.com/repos/Psy-Fer/buttery-eel/traffic/clones > buttery-eel/${YEAR}/${DATE}.json
      - name: blue-crab
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p blue-crab/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.KUVA_BUTTERYEEL_BLUECRAB }}" https://api.github.com/repos/Psy-Fer/blue-crab/traffic/clones > blue-crab/${YEAR}/${DATE}.json
      - name: f5c
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p f5c/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.TRAFFIC_2008 }}" https://api.github.com/repos/hasindu2008/f5c/traffic/clones > f5c/${YEAR}/${DATE}.json
      - name: slow5lib
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p slow5lib/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.TRAFFIC_2008 }}" https://api.github.com/repos/hasindu2008/slow5lib/traffic/clones > slow5lib/${YEAR}/${DATE}.json
      - name: slow5tools
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p slow5tools/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.TRAFFIC_2008 }}" https://api.github.com/repos/hasindu2008/slow5tools/traffic/clones > slow5tools/${YEAR}/${DATE}.json
      - name: sigtk
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p sigtk/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.TRAFFIC_2008 }}" https://api.github.com/repos/hasindu2008/sigtk/traffic/clones > sigtk/${YEAR}/${DATE}.json
      - name: squigulator
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p squigulator/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.TRAFFIC_2008 }}" https://api.github.com/repos/hasindu2008/squigulator/traffic/clones > squigulator/${YEAR}/${DATE}.json
      - name: cornetto
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p cornetto/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.TRAFFIC_2008 }}" https://api.github.com/repos/hasindu2008/cornetto/traffic/clones > cornetto/${YEAR}/${DATE}.json
      - name: slow5curl
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p slow5curl/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.BONFIRE }}" https://api.github.com/repos/BonsonW/slow5curl/traffic/clones > slow5curl/${YEAR}/${DATE}.json
      - name: slorado
        run: |
          DATE=$(date +"%d_%m_%Y")
          YEAR=$(echo $DATE | cut -d'_' -f3)
          mkdir -p slorado/${YEAR}
          curl -H "Authorization: Bearer ${{ secrets.BONFIRE }}" https://api.github.com/repos/BonsonW/slorado/traffic/clones > slorado/${YEAR}/${DATE}.json
      - name: get counts
        run: ./getcounts.sh
